name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Migrate test
        uses: ./.github/actions/sqitch
        with:
          command: deploy
          target: test
  Setup-Python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Python version
        run: |
          python_version=$(cat .python-version)
          echo "python_version=${python_version}" >> $GITHUB_ENV
      # - name: Set up Python ${{ env.python_version }}
      #   uses: actions/setup-python@v4
      #   cache: 'pip'
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - run: pip install -r requirements.txt
  Testing:
    needs: Setup-Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - run: pip install -r requirements.txt
      # - name: Set up Python ${{ env.python_version }}
      #   uses: actions/setup-python@v4
      #   cache: 'pip'
      # - run: pip install -r requirements.txt
      - name: Testing
        run: pytest
  Linter-and-format:
    needs: Setup-Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - run: pip install -r requirements.txt
      # - name: Set up Python ${{ env.python_version }}
      #   uses: actions/setup-python@v4
      #   cache: 'pip'
      # - run: pip install -r requirements.txt
      - name: Lint check
        run: ruff check --fix --select 'I,E,F,UP,B,SIM'
      - name: Format check
        run: ruff format --check
